import './globals.css'
import { Inter } from 'next/font/google'
import Nav from "@/app/components/Nav";
import {getServerSession} from "next-auth/next";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import Hydrate from "@/app/components/Hydrate";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className='mx-64'>
      <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
      </Hydrate>
      </body>
    </html>
  )
}
